package org.bouncycastle.oer.its.template.ieee1609dot2.basetypes;

import com.stub.StubApp;
import java.math.BigInteger;
import org.bouncycastle.asn1.ASN1Integer;
import org.bouncycastle.asn1.cmc.BodyPartID;
import org.bouncycastle.oer.OERDefinition;

/* loaded from: /home/loneobs/Code/Even/RE/even-apks/base/decrypted_dex/classes2.dex */
public class Ieee1609Dot2BaseTypes {
    public static final OERDefinition.Builder BasePublicEncryptionKey;
    public static final OERDefinition.Builder BitmapSsp;
    public static final OERDefinition.Builder BitmapSspRange;
    public static final OERDefinition.Builder CircularRegion;
    public static final OERDefinition.Builder CountryAndRegions;
    public static final OERDefinition.Builder CountryAndSubregions;
    public static final OERDefinition.Builder CountryOnly;
    public static final OERDefinition.Builder CrlSeries;
    public static final OERDefinition.Builder Duration;
    public static final OERDefinition.Builder EccP256CurvePoint;
    public static final OERDefinition.Builder EccP384CurvePoint;
    public static final OERDefinition.Builder EcdsaP256Signature;
    public static final OERDefinition.Builder EcdsaP384Signature;
    public static final OERDefinition.Builder EciesP256EncryptedKey;
    public static final OERDefinition.Builder Elevation;
    public static final OERDefinition.Builder EncryptionKey;
    public static final OERDefinition.Builder GeographicRegion;
    public static final OERDefinition.Builder GroupLinkageValue;
    public static final OERDefinition.Builder HashAlgorithm;
    public static final OERDefinition.Builder HashedId10;
    public static final OERDefinition.Builder HashedId3;
    public static final OERDefinition.Builder HashedId32;
    public static final OERDefinition.Builder HashedId8;
    public static final OERDefinition.Builder Hostname;
    public static final OERDefinition.Builder IValue;
    public static final OERDefinition.Builder IdentifiedRegion;
    public static final OERDefinition.Builder KnownLatitude;
    public static final OERDefinition.Builder KnownLongitude;
    public static final OERDefinition.Builder LaId;
    public static final OERDefinition.Builder Latitude;
    public static final OERDefinition.Builder LinkageSeed;
    public static final OERDefinition.Builder LinkageValue;
    public static final OERDefinition.Builder Longitude;
    public static final OERDefinition.Builder NinetyDegreeInt;
    public static final OERDefinition.Builder OneEightyDegreeInt;
    public static final OERDefinition.Builder Point256;
    public static final OERDefinition.Builder Point384;
    public static final OERDefinition.Builder PolygonalRegion;
    public static final OERDefinition.Builder Psid;
    public static final OERDefinition.Builder PsidSsp;
    public static final OERDefinition.Builder PsidSspRange;
    public static final OERDefinition.Builder PublicEncryptionKey;
    public static final OERDefinition.Builder PublicVerificationKey;
    public static final OERDefinition.Builder RectangularRegion;
    public static final OERDefinition.Builder RegionAndSubregions;
    public static final OERDefinition.Builder SequenceOfHashedId3;
    public static final OERDefinition.Builder SequenceOfHashedId8;
    public static final OERDefinition.Builder SequenceOfIdentifiedRegion;
    public static final OERDefinition.Builder SequenceOfOctetString;
    public static final OERDefinition.Builder SequenceOfPsid;
    public static final OERDefinition.Builder SequenceOfPsidSsp;
    public static final OERDefinition.Builder SequenceOfPsidSspRange;
    public static final OERDefinition.Builder SequenceOfRectangularRegion;
    public static final OERDefinition.Builder SequenceOfRegionAndSubregions;
    public static final OERDefinition.Builder SequenceOfUint16;
    public static final OERDefinition.Builder SequenceOfUint8;
    public static final OERDefinition.Builder ServiceSpecificPermissions;
    public static final OERDefinition.Builder Signature;
    public static final OERDefinition.Builder SspRange;
    public static final OERDefinition.Builder SubjectAssurance;
    public static final OERDefinition.Builder SymmAlgorithm;
    public static final OERDefinition.Builder SymmetricEncryptionKey;
    public static final OERDefinition.Builder ThreeDLocation;
    public static final OERDefinition.Builder Time32;
    public static final OERDefinition.Builder Time64;
    public static final OERDefinition.Builder TwoDLocation;
    public static final OERDefinition.Builder UINT16;
    public static final OERDefinition.Builder UINT3 = OERDefinition.integer(0, 7).typeName(StubApp.getString2(33496));
    public static final OERDefinition.Builder UINT32;
    public static final OERDefinition.Builder UINT64;
    public static final OERDefinition.Builder UINT8;
    public static final OERDefinition.Builder UnknownLatitude;
    public static final OERDefinition.Builder UnknownLongitude;
    public static final OERDefinition.Builder ValidityPeriod;

    static {
        OERDefinition.Builder typeName = OERDefinition.integer(0L, 255L).typeName(StubApp.getString2(33497));
        UINT8 = typeName;
        OERDefinition.Builder typeName2 = OERDefinition.integer(0L, 65535L).typeName(StubApp.getString2(33498));
        UINT16 = typeName2;
        OERDefinition.Builder typeName3 = OERDefinition.integer(0L, BodyPartID.bodyIdMax).typeName(StubApp.getString2(11867));
        UINT32 = typeName3;
        OERDefinition.Builder typeName4 = OERDefinition.integer(BigInteger.ZERO, new BigInteger(StubApp.getString2(33229))).typeName(StubApp.getString2(11861));
        UINT64 = typeName4;
        OERDefinition.Builder typeName5 = OERDefinition.seqof(typeName2).typeName(StubApp.getString2(33499));
        SequenceOfUint16 = typeName5;
        OERDefinition.Builder typeName6 = OERDefinition.seqof(typeName).typeName(StubApp.getString2(33500));
        SequenceOfUint8 = typeName6;
        OERDefinition.Builder typeName7 = OERDefinition.octets(3).typeName(StubApp.getString2(33501));
        HashedId3 = typeName7;
        OERDefinition.Builder typeName8 = OERDefinition.octets(8).typeName(StubApp.getString2(33502));
        HashedId8 = typeName8;
        HashedId10 = OERDefinition.octets(10).typeName(StubApp.getString2(33503));
        HashedId32 = OERDefinition.octets(32).typeName(StubApp.getString2(33504));
        SequenceOfHashedId3 = OERDefinition.seqof(typeName7).typeName(StubApp.getString2(33505));
        SequenceOfHashedId8 = OERDefinition.seqof(typeName8).typeName(StubApp.getString2(33506));
        OERDefinition.Builder typeName9 = typeName3.typeName(StubApp.getString2(33507));
        Time32 = typeName9;
        Time64 = typeName4.typeName(StubApp.getString2(33508));
        OERDefinition.Builder typeName10 = OERDefinition.choice(typeName2.label(StubApp.getString2(29603)), typeName2.label(StubApp.getString2(29604)), typeName2.label(StubApp.getString2(29605)), typeName2.label(StubApp.getString2(9690)), typeName2.label(StubApp.getString2(29606)), typeName2.label(StubApp.getString2(29607)), typeName2.label(StubApp.getString2(29608))).typeName(StubApp.getString2(3229));
        Duration = typeName10;
        ValidityPeriod = OERDefinition.seq(typeName9.label(StubApp.getString2(22724)), typeName10.label(StubApp.getString2(2091))).typeName(StubApp.getString2(33509));
        IValue = typeName2.copy().typeName(StubApp.getString2(33510));
        Hostname = OERDefinition.utf8String(0, 255).typeName(StubApp.getString2(33511));
        LinkageValue = OERDefinition.octets(9).typeName(StubApp.getString2(33512));
        GroupLinkageValue = OERDefinition.seq(OERDefinition.octets(4).label(StubApp.getString2(33513)), OERDefinition.octets(9).label(StubApp.getString2(1061))).typeName(StubApp.getString2(33514));
        LaId = OERDefinition.octets(2).typeName(StubApp.getString2(33515));
        LinkageSeed = OERDefinition.octets(16).typeName(StubApp.getString2(33516));
        OERDefinition.Builder octets = OERDefinition.octets(32);
        String string2 = StubApp.getString2(925);
        OERDefinition.Builder label = octets.label(string2);
        OERDefinition.Builder octets2 = OERDefinition.octets(32);
        String string22 = StubApp.getString2(4935);
        OERDefinition.Builder typeName11 = OERDefinition.seq(label, octets2.label(string22)).typeName(StubApp.getString2(33517));
        Point256 = typeName11;
        OERDefinition.Builder octets3 = OERDefinition.octets(32);
        String string23 = StubApp.getString2(33518);
        OERDefinition.Builder label2 = octets3.label(string23);
        OERDefinition.Builder nullValue = OERDefinition.nullValue();
        String string24 = StubApp.getString2(5284);
        OERDefinition.Builder label3 = nullValue.label(string24);
        OERDefinition.Builder octets4 = OERDefinition.octets(32);
        String string25 = StubApp.getString2(33519);
        OERDefinition.Builder label4 = octets4.label(string25);
        OERDefinition.Builder octets5 = OERDefinition.octets(32);
        String string26 = StubApp.getString2(33520);
        OERDefinition.Builder typeName12 = OERDefinition.choice(label2, label3, label4, octets5.label(string26), typeName11.label(StubApp.getString2(33521))).typeName(StubApp.getString2(33522));
        EccP256CurvePoint = typeName12;
        String string27 = StubApp.getString2(33523);
        OERDefinition.Builder label5 = typeName12.label(string27);
        OERDefinition.Builder octets6 = OERDefinition.octets(32);
        String string28 = StubApp.getString2(33524);
        OERDefinition.Builder typeName13 = OERDefinition.seq(label5, octets6.label(string28)).typeName(StubApp.getString2(33525));
        EcdsaP256Signature = typeName13;
        OERDefinition.Builder typeName14 = OERDefinition.seq(OERDefinition.octets(48).label(string2), OERDefinition.octets(48).label(string22)).typeName(StubApp.getString2(33526));
        Point384 = typeName14;
        OERDefinition.Builder typeName15 = OERDefinition.choice(OERDefinition.octets(48).label(string23), OERDefinition.nullValue().label(string24), OERDefinition.octets(48).label(string25), OERDefinition.octets(48).label(string26), typeName14.label(StubApp.getString2(33527))).typeName(StubApp.getString2(33528));
        EccP384CurvePoint = typeName15;
        OERDefinition.Builder typeName16 = OERDefinition.seq(typeName15.label(string27), OERDefinition.octets(48).label(string28)).typeName(StubApp.getString2(33529));
        EcdsaP384Signature = typeName16;
        Signature = OERDefinition.choice(typeName13.label(StubApp.getString2(33530)), typeName13.label(StubApp.getString2(33531)), OERDefinition.extension(typeName16.label(StubApp.getString2(33532)))).typeName(StubApp.getString2(30309));
        String string29 = StubApp.getString2(29602);
        OERDefinition.Builder typeName17 = OERDefinition.enumeration(OERDefinition.enumItem(string29), OERDefinition.extension(new Object[0])).typeName(StubApp.getString2(33533));
        SymmAlgorithm = typeName17;
        HashAlgorithm = OERDefinition.enumeration(OERDefinition.enumItem(StubApp.getString2(33057)), OERDefinition.extension(OERDefinition.enumItem(StubApp.getString2(33058)))).typeName(StubApp.getString2(33534));
        EciesP256EncryptedKey = OERDefinition.seq(typeName12.copy().label(StubApp.getString2(1316)), OERDefinition.octets(16).label(StubApp.getString2(2376)), OERDefinition.octets(16).label(StubApp.getString2(1310))).typeName(StubApp.getString2(33535));
        OERDefinition.Builder typeName18 = OERDefinition.choice(typeName12.label(StubApp.getString2(33414)), typeName12.label(StubApp.getString2(33415)), OERDefinition.extension(new Object[0])).typeName(StubApp.getString2(33536));
        BasePublicEncryptionKey = typeName18;
        OERDefinition.Builder typeName19 = OERDefinition.choice(OERDefinition.octets(16).label(string29), OERDefinition.extension(new Object[0])).typeName(StubApp.getString2(33537));
        SymmetricEncryptionKey = typeName19;
        OERDefinition.Builder typeName20 = OERDefinition.seq(typeName17.label(StubApp.getString2(33538)), typeName18.label(StubApp.getString2(33539))).typeName(StubApp.getString2(33540));
        PublicEncryptionKey = typeName20;
        EncryptionKey = OERDefinition.choice(typeName20.label(StubApp.getString2(33541)), typeName19.label(StubApp.getString2(33542))).typeName(StubApp.getString2(33543));
        PublicVerificationKey = OERDefinition.choice(typeName12.label(StubApp.getString2(33544)), typeName12.label(StubApp.getString2(33545)), OERDefinition.extension(typeName15.label(StubApp.getString2(33546)))).typeName(StubApp.getString2(33547));
        OERDefinition.Builder typeName21 = OERDefinition.integer().rangeToMAXFrom(0L).typeName(StubApp.getString2(33548));
        Psid = typeName21;
        OERDefinition.Builder typeName22 = OERDefinition.octets(0, 31).typeName(StubApp.getString2(33549));
        BitmapSsp = typeName22;
        OERDefinition.Builder unbounded = OERDefinition.octets().unbounded();
        String string210 = StubApp.getString2(7331);
        OERDefinition.Builder typeName23 = OERDefinition.choice(unbounded.label(string210), OERDefinition.extension(typeName22)).typeName(StubApp.getString2(33550));
        ServiceSpecificPermissions = typeName23;
        String string211 = StubApp.getString2(33472);
        OERDefinition.Builder typeName24 = OERDefinition.seq(typeName21.label(string211), OERDefinition.optional(typeName23.label(StubApp.getString2(33551)))).typeName(StubApp.getString2(33552));
        PsidSsp = typeName24;
        SequenceOfPsidSsp = OERDefinition.seqof(typeName24).typeName(StubApp.getString2(33553));
        SequenceOfPsid = OERDefinition.seqof(typeName21).typeName(StubApp.getString2(33554));
        OERDefinition.Builder typeName25 = OERDefinition.seqof(OERDefinition.octets().rangeToMAXFrom(0L)).typeName(StubApp.getString2(33555));
        SequenceOfOctetString = typeName25;
        OERDefinition.Builder typeName26 = OERDefinition.seq(OERDefinition.octets(1, 32).label(StubApp.getString2(33556)), OERDefinition.octets(1, 32).label(StubApp.getString2(33557))).typeName(StubApp.getString2(33558));
        BitmapSspRange = typeName26;
        OERDefinition.Builder typeName27 = OERDefinition.choice(typeName25.label(string210), OERDefinition.nullValue().label(StubApp.getString2(23002)), OERDefinition.extension(typeName26.label(StubApp.getString2(33559)))).typeName(StubApp.getString2(33560));
        SspRange = typeName27;
        OERDefinition.Builder typeName28 = OERDefinition.seq(typeName21.label(string211), OERDefinition.optional(typeName27.label(StubApp.getString2(33561)))).typeName(StubApp.getString2(33562));
        PsidSspRange = typeName28;
        SequenceOfPsidSspRange = OERDefinition.seqof(typeName28).typeName(StubApp.getString2(33563));
        SubjectAssurance = OERDefinition.octets(1).typeName(StubApp.getString2(33564));
        CrlSeries = typeName2.typeName(StubApp.getString2(33565));
        OERDefinition.Builder typeName29 = typeName2.typeName(StubApp.getString2(33566));
        CountryOnly = typeName29;
        String string212 = StubApp.getString2(33567);
        OERDefinition.Builder typeName30 = OERDefinition.seq(typeName29.label(string212), typeName6.label(StubApp.getString2(33568))).typeName(StubApp.getString2(33569));
        CountryAndRegions = typeName30;
        OERDefinition.Builder typeName31 = OERDefinition.seq(typeName.label(StubApp.getString2(2051)), typeName5.label(StubApp.getString2(33570))).typeName(StubApp.getString2(33571));
        RegionAndSubregions = typeName31;
        OERDefinition.Builder typeName32 = OERDefinition.seqof(typeName31).typeName(StubApp.getString2(33572));
        SequenceOfRegionAndSubregions = typeName32;
        OERDefinition.Builder typeName33 = OERDefinition.seq(typeName29.label(StubApp.getString2(223)), typeName32.label(StubApp.getString2(33573))).typeName(StubApp.getString2(33574));
        CountryAndSubregions = typeName33;
        OERDefinition.Builder typeName34 = OERDefinition.choice(typeName29.label(string212), typeName30.label(StubApp.getString2(33575)), typeName33.label(StubApp.getString2(33576)), OERDefinition.extension(new Object[0])).typeName(StubApp.getString2(33577));
        IdentifiedRegion = typeName34;
        OERDefinition.Builder typeName35 = OERDefinition.seqof(typeName34).typeName(StubApp.getString2(33578));
        SequenceOfIdentifiedRegion = typeName35;
        OERDefinition.Builder typeName36 = OERDefinition.integer(-1799999999L, 1800000001L).typeName(StubApp.getString2(33579));
        OneEightyDegreeInt = typeName36;
        KnownLongitude = typeName36.copy().typeName(StubApp.getString2(33580));
        UnknownLongitude = OERDefinition.integer().validSwitchValue(new ASN1Integer(1800000001L)).typeName(StubApp.getString2(33581));
        OERDefinition.Builder typeName37 = OERDefinition.integer(-900000000L, 900000001L).typeName(StubApp.getString2(33582));
        NinetyDegreeInt = typeName37;
        KnownLatitude = typeName37.copy().typeName(StubApp.getString2(33583));
        UnknownLatitude = OERDefinition.integer().validSwitchValue(new ASN1Integer(900000001L)).typeName(StubApp.getString2(33584));
        OERDefinition.Builder typeName38 = typeName2.typeName(StubApp.getString2(33585));
        Elevation = typeName38;
        OERDefinition.Builder typeName39 = typeName36.copy().typeName(StubApp.getString2(33586));
        Longitude = typeName39;
        OERDefinition.Builder typeName40 = typeName37.copy().typeName(StubApp.getString2(33587));
        Latitude = typeName40;
        String string213 = StubApp.getString2(2044);
        OERDefinition.Builder label6 = typeName40.label(string213);
        String string214 = StubApp.getString2(2043);
        ThreeDLocation = OERDefinition.seq(label6, typeName39.label(string214), typeName38.label(StubApp.getString2(33588))).typeName(StubApp.getString2(33589));
        OERDefinition.Builder typeName41 = OERDefinition.seq(typeName40.label(string213), typeName39.label(string214)).typeName(StubApp.getString2(33590));
        TwoDLocation = typeName41;
        OERDefinition.Builder typeName42 = OERDefinition.seq(typeName41.label(StubApp.getString2(33591)), typeName41.label(StubApp.getString2(33592))).typeName(StubApp.getString2(33593));
        RectangularRegion = typeName42;
        OERDefinition.Builder typeName43 = OERDefinition.seqof(typeName42).typeName(StubApp.getString2(33594));
        SequenceOfRectangularRegion = typeName43;
        OERDefinition.Builder typeName44 = OERDefinition.seq(typeName41.label(StubApp.getString2(6013)), typeName2.label(StubApp.getString2(33595))).typeName(StubApp.getString2(33596));
        CircularRegion = typeName44;
        OERDefinition.Builder typeName45 = OERDefinition.seqof(typeName41).rangeToMAXFrom(3L).typeName(StubApp.getString2(33597));
        PolygonalRegion = typeName45;
        GeographicRegion = OERDefinition.choice(typeName44.label(StubApp.getString2(33598)), typeName43.label(StubApp.getString2(33599)), typeName45.label(StubApp.getString2(33600)), typeName35.label(StubApp.getString2(33601)), OERDefinition.extension(new Object[0])).typeName(StubApp.getString2(33602));
    }
}
