package org.bouncycastle.operator;

import E1.a;
import com.stub.StubApp;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import org.bouncycastle.asn1.ASN1Encodable;
import org.bouncycastle.asn1.ASN1Integer;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.DERNull;
import org.bouncycastle.asn1.bc.BCObjectIdentifiers;
import org.bouncycastle.asn1.bsi.BSIObjectIdentifiers;
import org.bouncycastle.asn1.cms.CMSObjectIdentifiers;
import org.bouncycastle.asn1.cryptopro.CryptoProObjectIdentifiers;
import org.bouncycastle.asn1.eac.EACObjectIdentifiers;
import org.bouncycastle.asn1.edec.EdECObjectIdentifiers;
import org.bouncycastle.asn1.gm.GMObjectIdentifiers;
import org.bouncycastle.asn1.isara.IsaraObjectIdentifiers;
import org.bouncycastle.asn1.misc.MiscObjectIdentifiers;
import org.bouncycastle.asn1.nist.NISTObjectIdentifiers;
import org.bouncycastle.asn1.oiw.OIWObjectIdentifiers;
import org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import org.bouncycastle.asn1.pkcs.RSASSAPSSparams;
import org.bouncycastle.asn1.rosstandart.RosstandartObjectIdentifiers;
import org.bouncycastle.asn1.teletrust.TeleTrusTObjectIdentifiers;
import org.bouncycastle.asn1.x509.AlgorithmIdentifier;
import org.bouncycastle.asn1.x9.X9ObjectIdentifiers;
import org.bouncycastle.util.Strings;

/* loaded from: /home/loneobs/Code/Even/RE/even-apks/base/decrypted_dex/classes2.dex */
public class DefaultSignatureAlgorithmIdentifierFinder implements SignatureAlgorithmIdentifierFinder {
    private static final ASN1ObjectIdentifier ENCRYPTION_DSA;
    private static final ASN1ObjectIdentifier ENCRYPTION_ECDSA;
    private static final ASN1ObjectIdentifier ENCRYPTION_ECGOST3410;
    private static final ASN1ObjectIdentifier ENCRYPTION_ECGOST3410_2012_256;
    private static final ASN1ObjectIdentifier ENCRYPTION_ECGOST3410_2012_512;
    private static final ASN1ObjectIdentifier ENCRYPTION_GOST3410;
    private static final ASN1ObjectIdentifier ENCRYPTION_RSA_PSS;
    private static Map algorithms = new HashMap();
    private static Set noParams = new HashSet();
    private static Map params = new HashMap();
    private static Set pkcs15RsaEncryption = new HashSet();
    private static Map digestOids = new HashMap();
    private static final ASN1ObjectIdentifier ENCRYPTION_RSA = PKCSObjectIdentifiers.rsaEncryption;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = X9ObjectIdentifiers.id_dsa_with_sha1;
        ENCRYPTION_DSA = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = X9ObjectIdentifiers.ecdsa_with_SHA1;
        ENCRYPTION_ECDSA = aSN1ObjectIdentifier2;
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = PKCSObjectIdentifiers.id_RSASSA_PSS;
        ENCRYPTION_RSA_PSS = aSN1ObjectIdentifier3;
        ENCRYPTION_GOST3410 = CryptoProObjectIdentifiers.gostR3410_94;
        ENCRYPTION_ECGOST3410 = CryptoProObjectIdentifiers.gostR3410_2001;
        ENCRYPTION_ECGOST3410_2012_256 = RosstandartObjectIdentifiers.id_tc26_gost_3410_12_256;
        ENCRYPTION_ECGOST3410_2012_512 = RosstandartObjectIdentifiers.id_tc26_gost_3410_12_512;
        algorithms.put(StubApp.getString2(28200), MiscObjectIdentifiers.id_alg_composite);
        Map map = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = PKCSObjectIdentifiers.md2WithRSAEncryption;
        map.put(StubApp.getString2(32458), aSN1ObjectIdentifier4);
        algorithms.put(StubApp.getString2(32459), aSN1ObjectIdentifier4);
        Map map2 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = PKCSObjectIdentifiers.md5WithRSAEncryption;
        map2.put(StubApp.getString2(32461), aSN1ObjectIdentifier5);
        algorithms.put(StubApp.getString2(32462), aSN1ObjectIdentifier5);
        Map map3 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = PKCSObjectIdentifiers.sha1WithRSAEncryption;
        map3.put(StubApp.getString2(32465), aSN1ObjectIdentifier6);
        algorithms.put(StubApp.getString2(30425), aSN1ObjectIdentifier6);
        Map map4 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = PKCSObjectIdentifiers.sha224WithRSAEncryption;
        map4.put(StubApp.getString2(32466), aSN1ObjectIdentifier7);
        algorithms.put(StubApp.getString2(32467), aSN1ObjectIdentifier7);
        Map map5 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = PKCSObjectIdentifiers.sha256WithRSAEncryption;
        map5.put(StubApp.getString2(32468), aSN1ObjectIdentifier8);
        algorithms.put(StubApp.getString2(32469), aSN1ObjectIdentifier8);
        Map map6 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = PKCSObjectIdentifiers.sha384WithRSAEncryption;
        map6.put(StubApp.getString2(32470), aSN1ObjectIdentifier9);
        algorithms.put(StubApp.getString2(32471), aSN1ObjectIdentifier9);
        Map map7 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = PKCSObjectIdentifiers.sha512WithRSAEncryption;
        map7.put(StubApp.getString2(32472), aSN1ObjectIdentifier10);
        algorithms.put(StubApp.getString2(32473), aSN1ObjectIdentifier10);
        Map map8 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = PKCSObjectIdentifiers.sha512_224WithRSAEncryption;
        map8.put(StubApp.getString2(33771), aSN1ObjectIdentifier11);
        algorithms.put(StubApp.getString2(33772), aSN1ObjectIdentifier11);
        Map map9 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier12 = PKCSObjectIdentifiers.sha512_256WithRSAEncryption;
        map9.put(StubApp.getString2(33773), aSN1ObjectIdentifier12);
        algorithms.put(StubApp.getString2(33774), aSN1ObjectIdentifier12);
        Map map10 = algorithms;
        String string2 = StubApp.getString2(32474);
        map10.put(string2, aSN1ObjectIdentifier3);
        Map map11 = algorithms;
        String string22 = StubApp.getString2(32475);
        map11.put(string22, aSN1ObjectIdentifier3);
        Map map12 = algorithms;
        String string23 = StubApp.getString2(32476);
        map12.put(string23, aSN1ObjectIdentifier3);
        Map map13 = algorithms;
        String string24 = StubApp.getString2(32477);
        map13.put(string24, aSN1ObjectIdentifier3);
        Map map14 = algorithms;
        String string25 = StubApp.getString2(32478);
        map14.put(string25, aSN1ObjectIdentifier3);
        Map map15 = algorithms;
        String string26 = StubApp.getString2(33775);
        map15.put(string26, aSN1ObjectIdentifier3);
        Map map16 = algorithms;
        String string27 = StubApp.getString2(33776);
        map16.put(string27, aSN1ObjectIdentifier3);
        Map map17 = algorithms;
        String string28 = StubApp.getString2(33777);
        map17.put(string28, aSN1ObjectIdentifier3);
        Map map18 = algorithms;
        String string29 = StubApp.getString2(33778);
        map18.put(string29, aSN1ObjectIdentifier3);
        Map map19 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier13 = TeleTrusTObjectIdentifiers.rsaSignatureWithripemd160;
        map19.put(StubApp.getString2(32482), aSN1ObjectIdentifier13);
        algorithms.put(StubApp.getString2(32483), aSN1ObjectIdentifier13);
        Map map20 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier14 = TeleTrusTObjectIdentifiers.rsaSignatureWithripemd128;
        map20.put(StubApp.getString2(32480), aSN1ObjectIdentifier14);
        algorithms.put(StubApp.getString2(32481), aSN1ObjectIdentifier14);
        Map map21 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier15 = TeleTrusTObjectIdentifiers.rsaSignatureWithripemd256;
        map21.put(StubApp.getString2(32484), aSN1ObjectIdentifier15);
        algorithms.put(StubApp.getString2(32485), aSN1ObjectIdentifier15);
        algorithms.put(StubApp.getString2(32487), aSN1ObjectIdentifier);
        algorithms.put(StubApp.getString2(32488), aSN1ObjectIdentifier);
        Map map22 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier16 = NISTObjectIdentifiers.dsa_with_sha224;
        map22.put(StubApp.getString2(32489), aSN1ObjectIdentifier16);
        Map map23 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier17 = NISTObjectIdentifiers.dsa_with_sha256;
        map23.put(StubApp.getString2(32490), aSN1ObjectIdentifier17);
        Map map24 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier18 = NISTObjectIdentifiers.dsa_with_sha384;
        map24.put(StubApp.getString2(32491), aSN1ObjectIdentifier18);
        Map map25 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier19 = NISTObjectIdentifiers.dsa_with_sha512;
        map25.put(StubApp.getString2(32492), aSN1ObjectIdentifier19);
        Map map26 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier20 = NISTObjectIdentifiers.id_dsa_with_sha3_224;
        map26.put(StubApp.getString2(33711), aSN1ObjectIdentifier20);
        Map map27 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier21 = NISTObjectIdentifiers.id_dsa_with_sha3_256;
        map27.put(StubApp.getString2(33712), aSN1ObjectIdentifier21);
        Map map28 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier22 = NISTObjectIdentifiers.id_dsa_with_sha3_384;
        map28.put(StubApp.getString2(33713), aSN1ObjectIdentifier22);
        Map map29 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier23 = NISTObjectIdentifiers.id_dsa_with_sha3_512;
        map29.put(StubApp.getString2(33714), aSN1ObjectIdentifier23);
        Map map30 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier24 = NISTObjectIdentifiers.id_ecdsa_with_sha3_224;
        map30.put(StubApp.getString2(33707), aSN1ObjectIdentifier24);
        Map map31 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier25 = NISTObjectIdentifiers.id_ecdsa_with_sha3_256;
        map31.put(StubApp.getString2(33708), aSN1ObjectIdentifier25);
        Map map32 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier26 = NISTObjectIdentifiers.id_ecdsa_with_sha3_384;
        map32.put(StubApp.getString2(33709), aSN1ObjectIdentifier26);
        Map map33 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier27 = NISTObjectIdentifiers.id_ecdsa_with_sha3_512;
        map33.put(StubApp.getString2(33710), aSN1ObjectIdentifier27);
        Map map34 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier28 = NISTObjectIdentifiers.id_rsassa_pkcs1_v1_5_with_sha3_224;
        map34.put(StubApp.getString2(33703), aSN1ObjectIdentifier28);
        Map map35 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier29 = NISTObjectIdentifiers.id_rsassa_pkcs1_v1_5_with_sha3_256;
        map35.put(StubApp.getString2(33704), aSN1ObjectIdentifier29);
        Map map36 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier30 = NISTObjectIdentifiers.id_rsassa_pkcs1_v1_5_with_sha3_384;
        map36.put(StubApp.getString2(33705), aSN1ObjectIdentifier30);
        Map map37 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier31 = NISTObjectIdentifiers.id_rsassa_pkcs1_v1_5_with_sha3_512;
        map37.put(StubApp.getString2(33706), aSN1ObjectIdentifier31);
        algorithms.put(StubApp.getString2(33779), aSN1ObjectIdentifier28);
        algorithms.put(StubApp.getString2(33780), aSN1ObjectIdentifier29);
        algorithms.put(StubApp.getString2(33781), aSN1ObjectIdentifier30);
        algorithms.put(StubApp.getString2(33782), aSN1ObjectIdentifier31);
        algorithms.put(StubApp.getString2(32493), aSN1ObjectIdentifier2);
        algorithms.put(StubApp.getString2(32498), aSN1ObjectIdentifier2);
        Map map38 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier32 = X9ObjectIdentifiers.ecdsa_with_SHA224;
        map38.put(StubApp.getString2(32494), aSN1ObjectIdentifier32);
        Map map39 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier33 = X9ObjectIdentifiers.ecdsa_with_SHA256;
        map39.put(StubApp.getString2(32495), aSN1ObjectIdentifier33);
        Map map40 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier34 = X9ObjectIdentifiers.ecdsa_with_SHA384;
        map40.put(StubApp.getString2(32496), aSN1ObjectIdentifier34);
        Map map41 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier35 = X9ObjectIdentifiers.ecdsa_with_SHA512;
        map41.put(StubApp.getString2(32497), aSN1ObjectIdentifier35);
        Map map42 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier36 = CryptoProObjectIdentifiers.gostR3411_94_with_gostR3410_94;
        map42.put(StubApp.getString2(32499), aSN1ObjectIdentifier36);
        algorithms.put(StubApp.getString2(33697), aSN1ObjectIdentifier36);
        Map map43 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier37 = CryptoProObjectIdentifiers.gostR3411_94_with_gostR3410_2001;
        map43.put(StubApp.getString2(32501), aSN1ObjectIdentifier37);
        algorithms.put(StubApp.getString2(32502), aSN1ObjectIdentifier37);
        algorithms.put(StubApp.getString2(32503), aSN1ObjectIdentifier37);
        Map map44 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier38 = RosstandartObjectIdentifiers.id_tc26_signwithdigest_gost_3410_12_256;
        map44.put(StubApp.getString2(33698), aSN1ObjectIdentifier38);
        Map map45 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier39 = RosstandartObjectIdentifiers.id_tc26_signwithdigest_gost_3410_12_512;
        map45.put(StubApp.getString2(33699), aSN1ObjectIdentifier39);
        algorithms.put(StubApp.getString2(33783), aSN1ObjectIdentifier38);
        algorithms.put(StubApp.getString2(33784), aSN1ObjectIdentifier39);
        algorithms.put(StubApp.getString2(32721), aSN1ObjectIdentifier38);
        algorithms.put(StubApp.getString2(32722), aSN1ObjectIdentifier39);
        algorithms.put(StubApp.getString2(33785), aSN1ObjectIdentifier38);
        algorithms.put(StubApp.getString2(33786), aSN1ObjectIdentifier39);
        algorithms.put(StubApp.getString2(32729), EACObjectIdentifiers.id_TA_ECDSA_SHA_1);
        algorithms.put(StubApp.getString2(32730), EACObjectIdentifiers.id_TA_ECDSA_SHA_224);
        algorithms.put(StubApp.getString2(32731), EACObjectIdentifiers.id_TA_ECDSA_SHA_256);
        algorithms.put(StubApp.getString2(32732), EACObjectIdentifiers.id_TA_ECDSA_SHA_384);
        algorithms.put(StubApp.getString2(32733), EACObjectIdentifiers.id_TA_ECDSA_SHA_512);
        Map map46 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier40 = BCObjectIdentifiers.sphincs256_with_SHA3_512;
        map46.put(StubApp.getString2(33787), aSN1ObjectIdentifier40);
        Map map47 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier41 = BCObjectIdentifiers.sphincs256_with_SHA512;
        map47.put(StubApp.getString2(33788), aSN1ObjectIdentifier41);
        algorithms.put(StubApp.getString2(32723), BSIObjectIdentifiers.ecdsa_plain_SHA1);
        algorithms.put(StubApp.getString2(32728), BSIObjectIdentifiers.ecdsa_plain_RIPEMD160);
        Map map48 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier42 = BSIObjectIdentifiers.ecdsa_plain_SHA224;
        map48.put(StubApp.getString2(32724), aSN1ObjectIdentifier42);
        Map map49 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier43 = BSIObjectIdentifiers.ecdsa_plain_SHA256;
        map49.put(StubApp.getString2(32725), aSN1ObjectIdentifier43);
        Map map50 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier44 = BSIObjectIdentifiers.ecdsa_plain_SHA384;
        map50.put(StubApp.getString2(32726), aSN1ObjectIdentifier44);
        Map map51 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier45 = BSIObjectIdentifiers.ecdsa_plain_SHA512;
        map51.put(StubApp.getString2(32727), aSN1ObjectIdentifier45);
        Map map52 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier46 = BSIObjectIdentifiers.ecdsa_plain_SHA3_224;
        map52.put(StubApp.getString2(33789), aSN1ObjectIdentifier46);
        Map map53 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier47 = BSIObjectIdentifiers.ecdsa_plain_SHA3_256;
        map53.put(StubApp.getString2(33790), aSN1ObjectIdentifier47);
        Map map54 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier48 = BSIObjectIdentifiers.ecdsa_plain_SHA3_384;
        map54.put(StubApp.getString2(33791), aSN1ObjectIdentifier48);
        Map map55 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier49 = BSIObjectIdentifiers.ecdsa_plain_SHA3_512;
        map55.put(StubApp.getString2(33792), aSN1ObjectIdentifier49);
        Map map56 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier50 = EdECObjectIdentifiers.id_Ed25519;
        map56.put(StubApp.getString2(30119), aSN1ObjectIdentifier50);
        Map map57 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier51 = EdECObjectIdentifiers.id_Ed448;
        map57.put(StubApp.getString2(30117), aSN1ObjectIdentifier51);
        Map map58 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier52 = CMSObjectIdentifiers.id_RSASSA_PSS_SHAKE128;
        map58.put(StubApp.getString2(33793), aSN1ObjectIdentifier52);
        Map map59 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier53 = CMSObjectIdentifiers.id_RSASSA_PSS_SHAKE256;
        map59.put(StubApp.getString2(33794), aSN1ObjectIdentifier53);
        algorithms.put(StubApp.getString2(33795), aSN1ObjectIdentifier52);
        algorithms.put(StubApp.getString2(33796), aSN1ObjectIdentifier53);
        Map map60 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier54 = CMSObjectIdentifiers.id_ecdsa_with_shake128;
        map60.put(StubApp.getString2(33797), aSN1ObjectIdentifier54);
        Map map61 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier55 = CMSObjectIdentifiers.id_ecdsa_with_shake256;
        map61.put(StubApp.getString2(33798), aSN1ObjectIdentifier55);
        Map map62 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier56 = GMObjectIdentifiers.sm2sign_with_sha256;
        map62.put(StubApp.getString2(30214), aSN1ObjectIdentifier56);
        Map map63 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier57 = GMObjectIdentifiers.sm2sign_with_sm3;
        map63.put(StubApp.getString2(30217), aSN1ObjectIdentifier57);
        Map map64 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier58 = BCObjectIdentifiers.xmss_SHA256ph;
        map64.put(StubApp.getString2(33799), aSN1ObjectIdentifier58);
        Map map65 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier59 = BCObjectIdentifiers.xmss_SHA512ph;
        map65.put(StubApp.getString2(33800), aSN1ObjectIdentifier59);
        Map map66 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier60 = BCObjectIdentifiers.xmss_SHAKE128ph;
        map66.put(StubApp.getString2(33801), aSN1ObjectIdentifier60);
        Map map67 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier61 = BCObjectIdentifiers.xmss_SHAKE256ph;
        map67.put(StubApp.getString2(33802), aSN1ObjectIdentifier61);
        Map map68 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier62 = BCObjectIdentifiers.xmss_mt_SHA256ph;
        map68.put(StubApp.getString2(33803), aSN1ObjectIdentifier62);
        Map map69 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier63 = BCObjectIdentifiers.xmss_mt_SHA512ph;
        map69.put(StubApp.getString2(33804), aSN1ObjectIdentifier63);
        Map map70 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier64 = BCObjectIdentifiers.xmss_mt_SHAKE128ph;
        map70.put(StubApp.getString2(33805), aSN1ObjectIdentifier64);
        Map map71 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier65 = BCObjectIdentifiers.xmss_mt_SHAKE256ph;
        map71.put(StubApp.getString2(33806), aSN1ObjectIdentifier65);
        algorithms.put(StubApp.getString2(33807), aSN1ObjectIdentifier58);
        algorithms.put(StubApp.getString2(33808), aSN1ObjectIdentifier59);
        algorithms.put(StubApp.getString2(33809), aSN1ObjectIdentifier60);
        algorithms.put(StubApp.getString2(33810), aSN1ObjectIdentifier61);
        algorithms.put(StubApp.getString2(33811), aSN1ObjectIdentifier62);
        algorithms.put(StubApp.getString2(33812), aSN1ObjectIdentifier63);
        algorithms.put(StubApp.getString2(33813), aSN1ObjectIdentifier64);
        algorithms.put(StubApp.getString2(33814), aSN1ObjectIdentifier65);
        algorithms.put(StubApp.getString2(28198), PKCSObjectIdentifiers.id_alg_hss_lms_hashsig);
        Map map72 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier66 = IsaraObjectIdentifiers.id_alg_xmss;
        map72.put(StubApp.getString2(32734), aSN1ObjectIdentifier66);
        Map map73 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier67 = BCObjectIdentifiers.xmss_SHA256;
        map73.put(StubApp.getString2(33815), aSN1ObjectIdentifier67);
        Map map74 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier68 = BCObjectIdentifiers.xmss_SHA512;
        map74.put(StubApp.getString2(33816), aSN1ObjectIdentifier68);
        Map map75 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier69 = BCObjectIdentifiers.xmss_SHAKE128;
        map75.put(StubApp.getString2(33817), aSN1ObjectIdentifier69);
        Map map76 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier70 = BCObjectIdentifiers.xmss_SHAKE256;
        map76.put(StubApp.getString2(33818), aSN1ObjectIdentifier70);
        Map map77 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier71 = IsaraObjectIdentifiers.id_alg_xmssmt;
        map77.put(StubApp.getString2(32735), aSN1ObjectIdentifier71);
        Map map78 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier72 = BCObjectIdentifiers.xmss_mt_SHA256;
        map78.put(StubApp.getString2(33819), aSN1ObjectIdentifier72);
        Map map79 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier73 = BCObjectIdentifiers.xmss_mt_SHA512;
        map79.put(StubApp.getString2(33820), aSN1ObjectIdentifier73);
        Map map80 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier74 = BCObjectIdentifiers.xmss_mt_SHAKE128;
        map80.put(StubApp.getString2(33821), aSN1ObjectIdentifier74);
        Map map81 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier75 = BCObjectIdentifiers.xmss_mt_SHAKE256;
        map81.put(StubApp.getString2(33822), aSN1ObjectIdentifier75);
        Map map82 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier76 = BCObjectIdentifiers.sphincsPlus;
        map82.put(StubApp.getString2(33701), aSN1ObjectIdentifier76);
        algorithms.put(StubApp.getString2(30471), aSN1ObjectIdentifier76);
        Map map83 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier77 = BCObjectIdentifiers.dilithium2;
        map83.put(StubApp.getString2(33823), aSN1ObjectIdentifier77);
        Map map84 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier78 = BCObjectIdentifiers.dilithium3;
        map84.put(StubApp.getString2(33824), aSN1ObjectIdentifier78);
        Map map85 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier79 = BCObjectIdentifiers.dilithium5;
        map85.put(StubApp.getString2(33825), aSN1ObjectIdentifier79);
        Map map86 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier80 = BCObjectIdentifiers.dilithium2_aes;
        map86.put(StubApp.getString2(33826), aSN1ObjectIdentifier80);
        Map map87 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier81 = BCObjectIdentifiers.dilithium3_aes;
        map87.put(StubApp.getString2(33827), aSN1ObjectIdentifier81);
        Map map88 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier82 = BCObjectIdentifiers.dilithium5_aes;
        map88.put(StubApp.getString2(33828), aSN1ObjectIdentifier82);
        Map map89 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier83 = BCObjectIdentifiers.falcon_512;
        map89.put(StubApp.getString2(33829), aSN1ObjectIdentifier83);
        Map map90 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier84 = BCObjectIdentifiers.falcon_1024;
        map90.put(StubApp.getString2(33830), aSN1ObjectIdentifier84);
        Map map91 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier85 = BCObjectIdentifiers.picnic_signature;
        map91.put(StubApp.getString2(33831), aSN1ObjectIdentifier85);
        Map map92 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier86 = BCObjectIdentifiers.picnic_with_sha512;
        map92.put(StubApp.getString2(33832), aSN1ObjectIdentifier86);
        Map map93 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier87 = BCObjectIdentifiers.picnic_with_sha3_512;
        map93.put(StubApp.getString2(33833), aSN1ObjectIdentifier87);
        Map map94 = algorithms;
        ASN1ObjectIdentifier aSN1ObjectIdentifier88 = BCObjectIdentifiers.picnic_with_shake256;
        map94.put(StubApp.getString2(33834), aSN1ObjectIdentifier88);
        noParams.add(aSN1ObjectIdentifier2);
        noParams.add(aSN1ObjectIdentifier32);
        noParams.add(aSN1ObjectIdentifier33);
        noParams.add(aSN1ObjectIdentifier34);
        noParams.add(aSN1ObjectIdentifier35);
        noParams.add(aSN1ObjectIdentifier);
        noParams.add(OIWObjectIdentifiers.dsaWithSHA1);
        noParams.add(aSN1ObjectIdentifier16);
        noParams.add(aSN1ObjectIdentifier17);
        noParams.add(aSN1ObjectIdentifier18);
        noParams.add(aSN1ObjectIdentifier19);
        noParams.add(aSN1ObjectIdentifier20);
        noParams.add(aSN1ObjectIdentifier21);
        noParams.add(aSN1ObjectIdentifier22);
        noParams.add(aSN1ObjectIdentifier23);
        noParams.add(aSN1ObjectIdentifier24);
        noParams.add(aSN1ObjectIdentifier25);
        noParams.add(aSN1ObjectIdentifier26);
        noParams.add(aSN1ObjectIdentifier27);
        noParams.add(aSN1ObjectIdentifier42);
        noParams.add(aSN1ObjectIdentifier43);
        noParams.add(aSN1ObjectIdentifier44);
        noParams.add(aSN1ObjectIdentifier45);
        noParams.add(aSN1ObjectIdentifier46);
        noParams.add(aSN1ObjectIdentifier47);
        noParams.add(aSN1ObjectIdentifier48);
        noParams.add(aSN1ObjectIdentifier49);
        noParams.add(aSN1ObjectIdentifier36);
        noParams.add(aSN1ObjectIdentifier37);
        noParams.add(aSN1ObjectIdentifier38);
        noParams.add(aSN1ObjectIdentifier39);
        noParams.add(aSN1ObjectIdentifier41);
        noParams.add(aSN1ObjectIdentifier40);
        noParams.add(aSN1ObjectIdentifier76);
        Set set = noParams;
        ASN1ObjectIdentifier aSN1ObjectIdentifier89 = BCObjectIdentifiers.sphincsPlus_shake_256;
        set.add(aSN1ObjectIdentifier89);
        Set set2 = noParams;
        ASN1ObjectIdentifier aSN1ObjectIdentifier90 = BCObjectIdentifiers.sphincsPlus_sha_256;
        set2.add(aSN1ObjectIdentifier90);
        Set set3 = noParams;
        ASN1ObjectIdentifier aSN1ObjectIdentifier91 = BCObjectIdentifiers.sphincsPlus_sha_512;
        set3.add(aSN1ObjectIdentifier91);
        noParams.add(BCObjectIdentifiers.dilithium);
        noParams.add(aSN1ObjectIdentifier77);
        noParams.add(aSN1ObjectIdentifier78);
        noParams.add(aSN1ObjectIdentifier79);
        noParams.add(aSN1ObjectIdentifier80);
        noParams.add(aSN1ObjectIdentifier81);
        noParams.add(aSN1ObjectIdentifier82);
        noParams.add(BCObjectIdentifiers.falcon);
        noParams.add(aSN1ObjectIdentifier83);
        noParams.add(aSN1ObjectIdentifier84);
        noParams.add(aSN1ObjectIdentifier85);
        noParams.add(aSN1ObjectIdentifier86);
        noParams.add(aSN1ObjectIdentifier87);
        noParams.add(aSN1ObjectIdentifier88);
        noParams.add(aSN1ObjectIdentifier58);
        noParams.add(aSN1ObjectIdentifier59);
        noParams.add(aSN1ObjectIdentifier60);
        noParams.add(aSN1ObjectIdentifier61);
        noParams.add(aSN1ObjectIdentifier62);
        noParams.add(aSN1ObjectIdentifier63);
        noParams.add(aSN1ObjectIdentifier64);
        noParams.add(aSN1ObjectIdentifier65);
        noParams.add(aSN1ObjectIdentifier67);
        noParams.add(aSN1ObjectIdentifier68);
        noParams.add(aSN1ObjectIdentifier69);
        noParams.add(aSN1ObjectIdentifier70);
        noParams.add(aSN1ObjectIdentifier72);
        noParams.add(aSN1ObjectIdentifier73);
        noParams.add(aSN1ObjectIdentifier74);
        noParams.add(aSN1ObjectIdentifier75);
        noParams.add(aSN1ObjectIdentifier66);
        noParams.add(aSN1ObjectIdentifier71);
        noParams.add(BCObjectIdentifiers.qTESLA_p_I);
        noParams.add(BCObjectIdentifiers.qTESLA_p_III);
        noParams.add(aSN1ObjectIdentifier56);
        noParams.add(aSN1ObjectIdentifier57);
        noParams.add(aSN1ObjectIdentifier50);
        noParams.add(aSN1ObjectIdentifier51);
        noParams.add(aSN1ObjectIdentifier52);
        noParams.add(aSN1ObjectIdentifier53);
        noParams.add(aSN1ObjectIdentifier54);
        noParams.add(aSN1ObjectIdentifier55);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier6);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier7);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier8);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier9);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier10);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier14);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier13);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier15);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier28);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier29);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier30);
        pkcs15RsaEncryption.add(aSN1ObjectIdentifier31);
        ASN1ObjectIdentifier aSN1ObjectIdentifier92 = OIWObjectIdentifiers.idSHA1;
        DERNull dERNull = DERNull.INSTANCE;
        params.put(string2, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier92, dERNull), 20));
        ASN1ObjectIdentifier aSN1ObjectIdentifier93 = NISTObjectIdentifiers.id_sha224;
        params.put(string22, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier93, dERNull), 28));
        ASN1ObjectIdentifier aSN1ObjectIdentifier94 = NISTObjectIdentifiers.id_sha256;
        params.put(string23, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier94, dERNull), 32));
        ASN1ObjectIdentifier aSN1ObjectIdentifier95 = NISTObjectIdentifiers.id_sha384;
        params.put(string24, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier95, dERNull), 48));
        ASN1ObjectIdentifier aSN1ObjectIdentifier96 = NISTObjectIdentifiers.id_sha512;
        params.put(string25, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier96, dERNull), 64));
        ASN1ObjectIdentifier aSN1ObjectIdentifier97 = NISTObjectIdentifiers.id_sha3_224;
        params.put(string26, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier97, dERNull), 28));
        ASN1ObjectIdentifier aSN1ObjectIdentifier98 = NISTObjectIdentifiers.id_sha3_256;
        params.put(string27, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier98, dERNull), 32));
        ASN1ObjectIdentifier aSN1ObjectIdentifier99 = NISTObjectIdentifiers.id_sha3_384;
        params.put(string28, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier99, dERNull), 48));
        ASN1ObjectIdentifier aSN1ObjectIdentifier100 = NISTObjectIdentifiers.id_sha3_512;
        params.put(string29, createPSSParams(new AlgorithmIdentifier(aSN1ObjectIdentifier100, dERNull), 64));
        digestOids.put(aSN1ObjectIdentifier7, aSN1ObjectIdentifier93);
        digestOids.put(aSN1ObjectIdentifier8, aSN1ObjectIdentifier94);
        digestOids.put(aSN1ObjectIdentifier9, aSN1ObjectIdentifier95);
        digestOids.put(aSN1ObjectIdentifier10, aSN1ObjectIdentifier96);
        digestOids.put(aSN1ObjectIdentifier16, aSN1ObjectIdentifier93);
        digestOids.put(aSN1ObjectIdentifier17, aSN1ObjectIdentifier94);
        digestOids.put(aSN1ObjectIdentifier18, aSN1ObjectIdentifier95);
        digestOids.put(aSN1ObjectIdentifier19, aSN1ObjectIdentifier96);
        digestOids.put(aSN1ObjectIdentifier20, aSN1ObjectIdentifier97);
        digestOids.put(aSN1ObjectIdentifier21, aSN1ObjectIdentifier98);
        digestOids.put(aSN1ObjectIdentifier22, aSN1ObjectIdentifier99);
        digestOids.put(aSN1ObjectIdentifier23, aSN1ObjectIdentifier100);
        digestOids.put(aSN1ObjectIdentifier24, aSN1ObjectIdentifier97);
        digestOids.put(aSN1ObjectIdentifier25, aSN1ObjectIdentifier98);
        digestOids.put(aSN1ObjectIdentifier26, aSN1ObjectIdentifier99);
        digestOids.put(aSN1ObjectIdentifier27, aSN1ObjectIdentifier100);
        digestOids.put(aSN1ObjectIdentifier28, aSN1ObjectIdentifier97);
        digestOids.put(aSN1ObjectIdentifier29, aSN1ObjectIdentifier98);
        digestOids.put(aSN1ObjectIdentifier30, aSN1ObjectIdentifier99);
        digestOids.put(aSN1ObjectIdentifier31, aSN1ObjectIdentifier100);
        digestOids.put(aSN1ObjectIdentifier4, PKCSObjectIdentifiers.md2);
        digestOids.put(PKCSObjectIdentifiers.md4WithRSAEncryption, PKCSObjectIdentifiers.md4);
        digestOids.put(aSN1ObjectIdentifier5, PKCSObjectIdentifiers.md5);
        digestOids.put(aSN1ObjectIdentifier6, aSN1ObjectIdentifier92);
        digestOids.put(aSN1ObjectIdentifier14, TeleTrusTObjectIdentifiers.ripemd128);
        digestOids.put(aSN1ObjectIdentifier13, TeleTrusTObjectIdentifiers.ripemd160);
        digestOids.put(aSN1ObjectIdentifier15, TeleTrusTObjectIdentifiers.ripemd256);
        Map map95 = digestOids;
        ASN1ObjectIdentifier aSN1ObjectIdentifier101 = CryptoProObjectIdentifiers.gostR3411;
        map95.put(aSN1ObjectIdentifier36, aSN1ObjectIdentifier101);
        digestOids.put(aSN1ObjectIdentifier37, aSN1ObjectIdentifier101);
        digestOids.put(aSN1ObjectIdentifier38, RosstandartObjectIdentifiers.id_tc26_gost_3411_12_256);
        digestOids.put(aSN1ObjectIdentifier39, RosstandartObjectIdentifiers.id_tc26_gost_3411_12_512);
        Map map96 = digestOids;
        ASN1ObjectIdentifier aSN1ObjectIdentifier102 = NISTObjectIdentifiers.id_shake256;
        map96.put(aSN1ObjectIdentifier89, aSN1ObjectIdentifier102);
        digestOids.put(aSN1ObjectIdentifier90, aSN1ObjectIdentifier94);
        digestOids.put(aSN1ObjectIdentifier91, aSN1ObjectIdentifier96);
        digestOids.put(aSN1ObjectIdentifier56, aSN1ObjectIdentifier94);
        digestOids.put(aSN1ObjectIdentifier57, GMObjectIdentifiers.sm3);
        Map map97 = digestOids;
        ASN1ObjectIdentifier aSN1ObjectIdentifier103 = NISTObjectIdentifiers.id_shake128;
        map97.put(aSN1ObjectIdentifier52, aSN1ObjectIdentifier103);
        digestOids.put(aSN1ObjectIdentifier53, aSN1ObjectIdentifier102);
        digestOids.put(aSN1ObjectIdentifier54, aSN1ObjectIdentifier103);
        digestOids.put(aSN1ObjectIdentifier55, aSN1ObjectIdentifier102);
    }

    private static RSASSAPSSparams createPSSParams(AlgorithmIdentifier algorithmIdentifier, int i3) {
        return new RSASSAPSSparams(algorithmIdentifier, new AlgorithmIdentifier(PKCSObjectIdentifiers.id_mgf1, algorithmIdentifier), new ASN1Integer(i3), new ASN1Integer(1L));
    }

    private static AlgorithmIdentifier generate(String str) {
        String upperCase = Strings.toUpperCase(str);
        ASN1ObjectIdentifier aSN1ObjectIdentifier = (ASN1ObjectIdentifier) algorithms.get(upperCase);
        if (aSN1ObjectIdentifier != null) {
            return noParams.contains(aSN1ObjectIdentifier) ? new AlgorithmIdentifier(aSN1ObjectIdentifier) : params.containsKey(upperCase) ? new AlgorithmIdentifier(aSN1ObjectIdentifier, (ASN1Encodable) params.get(upperCase)) : new AlgorithmIdentifier(aSN1ObjectIdentifier, DERNull.INSTANCE);
        }
        throw new IllegalArgumentException(a.j(StubApp.getString2(33835), upperCase));
    }

    @Override // org.bouncycastle.operator.SignatureAlgorithmIdentifierFinder
    public AlgorithmIdentifier find(String str) {
        return generate(str);
    }
}
