package org.bouncycastle.crypto.examples;

import com.stub.StubApp;
import java.io.PrintStream;
import java.math.BigInteger;
import java.security.SecureRandom;
import org.bouncycastle.crypto.CryptoException;
import org.bouncycastle.crypto.agreement.jpake.JPAKEParticipant;
import org.bouncycastle.crypto.agreement.jpake.JPAKEPrimeOrderGroup;
import org.bouncycastle.crypto.agreement.jpake.JPAKEPrimeOrderGroups;
import org.bouncycastle.crypto.agreement.jpake.JPAKERound1Payload;
import org.bouncycastle.crypto.agreement.jpake.JPAKERound2Payload;
import org.bouncycastle.crypto.agreement.jpake.JPAKERound3Payload;
import org.bouncycastle.crypto.digests.SHA256Digest;

/* loaded from: /home/loneobs/Code/Even/RE/even-apks/base/decrypted_dex/classes2.dex */
public class JPAKEExample {
    private static BigInteger deriveSessionKey(BigInteger bigInteger) {
        SHA256Digest sHA256Digest = new SHA256Digest();
        byte[] byteArray = bigInteger.toByteArray();
        byte[] bArr = new byte[sHA256Digest.getDigestSize()];
        sHA256Digest.update(byteArray, 0, byteArray.length);
        sHA256Digest.doFinal(bArr, 0);
        return new BigInteger(bArr);
    }

    public static void main(String[] strArr) throws CryptoException {
        JPAKEPrimeOrderGroup jPAKEPrimeOrderGroup = JPAKEPrimeOrderGroups.NIST_3072;
        BigInteger p8 = jPAKEPrimeOrderGroup.getP();
        BigInteger q10 = jPAKEPrimeOrderGroup.getQ();
        BigInteger g10 = jPAKEPrimeOrderGroup.getG();
        System.out.println(StubApp.getString2(28817));
        System.out.println(StubApp.getString2(28818));
        PrintStream printStream = System.out;
        StringBuilder sb2 = new StringBuilder(StubApp.getString2(28819));
        sb2.append(p8.bitLength());
        String string2 = StubApp.getString2(28820);
        sb2.append(string2);
        sb2.append(p8.toString(16));
        printStream.println(sb2.toString());
        System.out.println(StubApp.getString2(28821) + q10.bitLength() + string2 + q10.toString(16));
        System.out.println(StubApp.getString2(28822) + p8.bitLength() + string2 + g10.toString(16));
        PrintStream printStream2 = System.out;
        StringBuilder sb3 = new StringBuilder(StubApp.getString2(28823));
        sb3.append(p8.mod(q10).toString(16));
        printStream2.println(sb3.toString());
        System.out.println(StubApp.getString2(28824) + g10.modPow(q10, p8).toString(16));
        System.out.println("");
        System.out.println(StubApp.getString2(28825));
        SHA256Digest sHA256Digest = new SHA256Digest();
        SecureRandom secureRandom = new SecureRandom();
        String string22 = StubApp.getString2(28826);
        String string23 = StubApp.getString2(6750);
        JPAKEParticipant jPAKEParticipant = new JPAKEParticipant(string22, string23.toCharArray(), jPAKEPrimeOrderGroup, sHA256Digest, secureRandom);
        JPAKEParticipant jPAKEParticipant2 = new JPAKEParticipant(StubApp.getString2(28827), string23.toCharArray(), jPAKEPrimeOrderGroup, sHA256Digest, secureRandom);
        JPAKERound1Payload createRound1PayloadToSend = jPAKEParticipant.createRound1PayloadToSend();
        JPAKERound1Payload createRound1PayloadToSend2 = jPAKEParticipant2.createRound1PayloadToSend();
        System.out.println(StubApp.getString2(28828));
        PrintStream printStream3 = System.out;
        String string24 = StubApp.getString2(28829);
        printStream3.println(string24);
        System.out.println(StubApp.getString2(28830) + createRound1PayloadToSend.getGx1().toString(16));
        System.out.println(StubApp.getString2(28831) + createRound1PayloadToSend.getGx2().toString(16));
        PrintStream printStream4 = System.out;
        StringBuilder sb4 = new StringBuilder(StubApp.getString2(28832));
        sb4.append(createRound1PayloadToSend.getKnowledgeProofForX1()[0].toString(16));
        String string25 = StubApp.getString2(28833);
        sb4.append(string25);
        sb4.append(createRound1PayloadToSend.getKnowledgeProofForX1()[1].toString(16));
        String string26 = StubApp.getString2(265);
        sb4.append(string26);
        printStream4.println(sb4.toString());
        System.out.println(StubApp.getString2(28834) + createRound1PayloadToSend.getKnowledgeProofForX2()[0].toString(16) + string25 + createRound1PayloadToSend.getKnowledgeProofForX2()[1].toString(16) + string26);
        System.out.println("");
        PrintStream printStream5 = System.out;
        String string27 = StubApp.getString2(28835);
        printStream5.println(string27);
        System.out.println(StubApp.getString2(28836) + createRound1PayloadToSend2.getGx1().toString(16));
        System.out.println(StubApp.getString2(28837) + createRound1PayloadToSend2.getGx2().toString(16));
        System.out.println(StubApp.getString2(28838) + createRound1PayloadToSend2.getKnowledgeProofForX1()[0].toString(16) + string25 + createRound1PayloadToSend2.getKnowledgeProofForX1()[1].toString(16) + string26);
        System.out.println(StubApp.getString2(28839) + createRound1PayloadToSend2.getKnowledgeProofForX2()[0].toString(16) + string25 + createRound1PayloadToSend2.getKnowledgeProofForX2()[1].toString(16) + string26);
        System.out.println("");
        jPAKEParticipant.validateRound1PayloadReceived(createRound1PayloadToSend2);
        System.out.println(StubApp.getString2(28840));
        System.out.println(StubApp.getString2(28841));
        System.out.println(StubApp.getString2(28842));
        System.out.println("");
        jPAKEParticipant2.validateRound1PayloadReceived(createRound1PayloadToSend);
        System.out.println(StubApp.getString2(28843));
        System.out.println(StubApp.getString2(28844));
        System.out.println(StubApp.getString2(28845));
        System.out.println("");
        JPAKERound2Payload createRound2PayloadToSend = jPAKEParticipant.createRound2PayloadToSend();
        JPAKERound2Payload createRound2PayloadToSend2 = jPAKEParticipant2.createRound2PayloadToSend();
        System.out.println(StubApp.getString2(28846));
        System.out.println(string24);
        System.out.println(StubApp.getString2(28847) + createRound2PayloadToSend.getA().toString(16));
        PrintStream printStream6 = System.out;
        StringBuilder sb5 = new StringBuilder(StubApp.getString2(28848));
        sb5.append(createRound2PayloadToSend.getKnowledgeProofForX2s()[0].toString(16));
        String string28 = StubApp.getString2(28849);
        sb5.append(string28);
        sb5.append(createRound2PayloadToSend.getKnowledgeProofForX2s()[1].toString(16));
        sb5.append(string26);
        printStream6.println(sb5.toString());
        System.out.println("");
        System.out.println(StubApp.getString2(28850));
        System.out.println(StubApp.getString2(28851) + createRound2PayloadToSend2.getA().toString(16));
        System.out.println(StubApp.getString2(28852) + createRound2PayloadToSend2.getKnowledgeProofForX2s()[0].toString(16) + string28 + createRound2PayloadToSend2.getKnowledgeProofForX2s()[1].toString(16) + string26);
        System.out.println("");
        jPAKEParticipant.validateRound2PayloadReceived(createRound2PayloadToSend2);
        System.out.println(StubApp.getString2(28853));
        jPAKEParticipant2.validateRound2PayloadReceived(createRound2PayloadToSend);
        System.out.println(StubApp.getString2(28854));
        BigInteger calculateKeyingMaterial = jPAKEParticipant.calculateKeyingMaterial();
        BigInteger calculateKeyingMaterial2 = jPAKEParticipant2.calculateKeyingMaterial();
        System.out.println(StubApp.getString2(28855));
        System.out.println(StubApp.getString2(28856) + calculateKeyingMaterial.toString(16));
        System.out.println(StubApp.getString2(28857) + calculateKeyingMaterial2.toString(16));
        System.out.println();
        deriveSessionKey(calculateKeyingMaterial);
        deriveSessionKey(calculateKeyingMaterial2);
        JPAKERound3Payload createRound3PayloadToSend = jPAKEParticipant.createRound3PayloadToSend(calculateKeyingMaterial);
        JPAKERound3Payload createRound3PayloadToSend2 = jPAKEParticipant2.createRound3PayloadToSend(calculateKeyingMaterial2);
        System.out.println(StubApp.getString2(28858));
        System.out.println(string24);
        PrintStream printStream7 = System.out;
        String string29 = StubApp.getString2(28859);
        printStream7.println(string29 + createRound3PayloadToSend.getMacTag().toString(16));
        System.out.println("");
        System.out.println(string27);
        System.out.println(string29 + createRound3PayloadToSend2.getMacTag().toString(16));
        System.out.println("");
        jPAKEParticipant.validateRound3PayloadReceived(createRound3PayloadToSend2, calculateKeyingMaterial);
        System.out.println(StubApp.getString2(28860));
        jPAKEParticipant2.validateRound3PayloadReceived(createRound3PayloadToSend, calculateKeyingMaterial2);
        System.out.println(StubApp.getString2(28861));
        System.out.println();
        System.out.println(StubApp.getString2(28862));
    }
}
